apiVersion: v1
kind: Service
metadata:
  name: tu-sofia-pis-2023-471223093
  labels:
    app: tu-sofia-pis-2023-471223093
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: tu-sofia-pis-2023-471223093
